name: Upload Backend Release Assets

on: 
  release: 
    types: [created]

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    working-directory: ./backend
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Build backend
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-gnu
      - name: Compress backend
        run: tar -czf ./target/release/backend backend_x86_64_linux.tar.gz
      - name: Upload Asset
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./backend_x86_64_linux.tar.gz
          asset_name: backend_x86_64_linux.tar.gz
          asset_content_type: application/gzip
