name: Upload Website Release Assets

on: 
  release: 
    types: [created]

defaults:
  run:
    working-directory: ./website

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Build website
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Compress website
        run: tar -czf website/target/release/website website_x86_64_linux.tar.gz
      - name: Upload Asset
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./website/website_x86_64_linux.tar.gz
          asset_name: website_x86_64_linux.tar.gz
          asset_content_type: application/gzip
