name: Upload Backend Release Assets

on: 
  release: 
    types: [created]

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Build backend
        run: cargo build --release --target x86_64-unknown-linux-gnu
        env:
          SQLX_OFFLINE: true
      - name: Upload Asset
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./backend/target/x86_64-unknown-linux-gnu/release/backend
          asset_name: backend_${{ env.GITHUB_REF }}_x86_64_linux
          asset_content_type: application/octet-stream
